### ISSUE TITLE
Node current version is not compatible with the Dockerfile in deploy.sh

### ISSUE THREAD

**Issue by lc3t35** [waitingkuo/docker-meteor#1]
When you install node with 

```
RUN apt-get install -y nodejs
```

it installs node 0.10.25 which is currently not compatible with meteor.
i suggest the following modifications, that allow to handle the needed version of nodejs

```
RUN add-apt-repository -y ppa:chris-lea/node.js
RUN apt-get update
RUN apt-get install -y nodejs
RUN apt-get install -y curl 
RUN npm cache clean -f
RUN npm install -g n
RUN n 0.10.24
```

**Comment by waitingkuo** [comment]
Hi, seems meteor supports node with version larger than 0.10.24 now.
So I'll not modify it.

Thank you for advising
